let list={};
list.names=[
        "Alina",
        "Amelie",
        "Amy",
        "Anna",
        "Charlotte",
        "Clara",
        "Elisa",
        "Ella",
        "Emelie",
        "Emely",
        "Emilia",
        "Emily",
        "Emilie",
        "Emma",
        "Frida",
        "Frieda",
        "Greta",
        "Hannah",
        "Hanna",
        "Helena",
        "Ida",
        "Isabel",
        "Isabell",
        "Isabella",
        "Isabelle",
        "Jana",
        "Johanna",
        "Julia",
        "Klara",
        "Lara",
        "Laura",
        "Lea",
        "Leah",
        "Lena",
        "Leni",
        "Leonie",
        "Lia",
        "Liah",
        "Lilli",
        "Julian",
        "Karl",
        "Lennard",
        "Lennart",
        "Leo",
        "Leon",
        "Liam",
        "Linus",
        "Louis",
        "Luca",
        "Lucas",
        "Luis",
        "Luka",
        "Lukas",
        "Mads",
        "Mats",
        "Matteo",
        "Max",
        "Maximilian",
        "Mika",
        "Moritz",
        "Nick",
        "Niclas",
        "Nico",
        "Niklas",
        "Niko",
        "Noah",
        "Oscar",
        "Oskar",
        "Paul",
        "Philipp",
        "Rafael",
        "Raphael",
        "Samuel",
        "Simon",
        "Theo",
        "Till",
        "Tim",
        "Tom",
        "Vincent",
        "Yannic",
        "Yannick",
]

list.surnames=[
          "Aardema", "Aarestad", "Aarhus", "Aaron", "Aarons", 
          "Aaronson", "Aarsvold", "Aas", "Aasby", "Aase", 
          "Aasen", "Aavang", "Abad", "Abadi", "Abadie", 
          "Abair", "Abaja", "Abajian", "Abalos", "Abaloz", 
          "Abar", "Abarca", "Abare", "Abascal", "Abasta",
          "Abate", "Abati", "Abatiell", "Abato", "Abatti",
          "Abaunza", "Abaya", "Abbadessa", "Abbamonte", "Abbas", 
          "Abbasi", "Abbassi", "Abbate", "Abbatiello", "Abbay", 
          "Abbe", "Abbed", "Abbenante", "Abbey","Bedker", 
          "Bedlion", "Bednar", "Bednarczyk", "Bednarek", "Bednarik",
          "Bednarowicz", "Bednarski", "Bednarz", "Bedner", "Bedney",
          "Bednorz", "Bedocs", "Bedoka", "Bedolla", "Bedonie",
          "Bedor", "Bedore", "Bedoya", "Bedre", "Bedrosian", 
          "Bedsaul", "Bedsole", "Bedson", "Bedward", "Bedwell", 
          "Bee", "Beebe", "Beebee", "Beebout", "Beech",
          "Beecham", "Beecher", "Beeching", "Beechler", "Beechner",
                 
]